shoppers/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from adminside.views import *
from userside.views import *

urlpatterns = [
    path('login/',login),
    path('',user_login),
    path('register/',register),
    path('dashboard/',dashboard),
    path('addadmin/',addadmin),
    path('edit_profile/<int:edit_id>',edit_profile),
    path('adminuserdata/',adminuserdata),
    path('logout/',logout),
    path('home/',home),


    path('slider/',slider),
    path('view_slider/',view_slider),
    path('delete_slide/<int:del_id2>',delete_slide),
    path('edit_slide/<int:edit_id2>',edit_slide),


    path('catagory/<int:cat_id>/', catagory),
    path('add_categorie/',add_categorie),
    path('view_categorie/',view_categorie),
    path('delete_categorie/<int:del_id3>',delete_categorie),
    path('edit_categorie/<int:edit_id3>',edit_categorie),


    path('cart/',cart),
    path('add_cart/<int:prod_id>',add_cart_func),
    path('add_like/<int:prod_id>',add_like),
    path('like',like),
   
    path('delete_cart/<int:del_id5>',delete_cart),
    path('delete_review/<int:del_id6>',delete_review),
    path('delete_like/<int:del_id7>',delete_like),
    path('edit_cart/<int:edit_id5>',edit_cart),

    path('checkout/',checkout),
    path('product_detail/<int:product_id>/',product_detail),
    
    path('contact/',contactpage),
    path('view_contact/',view_contact),

    path('shop/',shop),
    # path('product/<int:product_id>/',product),

    path('add_product/',add_product),
    path('view_product/',view_product),
    path('view_comment/',view_comment),
    path('edit_product/<int:edit_id4>',edit_product),
    path('delete_product/<int:del_id4>',delete_product),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

userside/models.py
from django.db import models
from django.forms import ModelForm
from django import forms
# Create your models here.

class sliders(models.Model):
    title = models.CharField(max_length=100)
    desc = models.CharField(max_length=1000)
    image = models.FileField(upload_to='./media/')

class sliderModelForm(ModelForm):
    class Meta:
        model = sliders
        fields = ["title","desc","image"]


    
class categories(models.Model):
    title = models.CharField(max_length=100)
    image = models.FileField(upload_to='./media/')

    def __str__(self):
        return self.title 
    
class categorieModelForm(ModelForm):
    class Meta:
        model = categories
        fields = ["title","image"]
        
class products(models.Model):
    cat_id=models.ForeignKey(categories,on_delete=models.CASCADE, default=0)
    name=models.CharField(max_length=1000)
    price=models.CharField(max_length=1000)
    desc = models.CharField(max_length=1000)
    image = models.FileField(upload_to='./media/')

    
class productModelForm(ModelForm):
    class Meta:
        model=products
        fields=["cat_id","name","price","desc","image"]

    
class carts(models.Model):
    product_id=models.ForeignKey(products,on_delete=models.CASCADE, default=0)
    price = models.CharField(max_length=1000)
    qty = models.CharField(max_length=1000)
    user_id= models.IntegerField(default=0)
    def total_cost(self):
        return int(self.qty) * int(self.price)
    
  

class cartModelForm(ModelForm):
    class Meta:
        model=carts
        fields=["product_id","price","qty","user_id"]

class likes(models.Model):
    product_id=models.ForeignKey(products,on_delete=models.CASCADE, default=0)
    price = models.CharField(max_length=1000)
    user_id= models.IntegerField(default=0)

class likeModelForm(ModelForm):
    class Meta:
        model=likes
        fields=["product_id","price","user_id"]   

class contact(models.Model):
    name = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    subject = models.CharField(max_length=100)
    msg = models.CharField(max_length=300)
    password = models.CharField(max_length=100)

class review(models.Model):
    fullname = models.CharField(max_length=100)
    email = models.CharField(max_length=100)
    comment = models.CharField(max_length=300)
    product = models.ForeignKey(products,default=13,on_delete=models.CASCADE)
    rating = models.IntegerField()
    user_id= models.IntegerField(default=0)

    

userside/views.py
from django.shortcuts import render,redirect
from userside.models import *
from django.db.models import Sum


# Create your views here.
def home(request):
    all_slides = sliders.objects.all()
    all_categorie = categories.objects.all()
    all_product = products.objects.all()[:4]
    
    # catagory = categories.objects.filter(id=cat_id).get()
    # catagory_products = products.objects.filter(cat_id=catagory)
    
    # categories 
    pro_cats=categories.objects.all()
    page_id =  request.session['page_id']
    page = contact.objects.filter(id=page_id).get()

    user_id = request.session.get('page_id')
    all_carts = carts.objects.filter(user_id=user_id)
    total_cart = all_carts.aggregate(total=Sum('qty'))['total'] or 0

    all_likes = likes.objects.filter(user_id=user_id)
    total_like = all_likes.aggregate(total=Sum('user_id'))['total'] or 0
    # return render(request,'home.html',{ 'catagory_products': catagory_products, 'catagory': catagory,'total_cart':total_cart,'cat':pro_cats,'sliders':all_slides,'categories':all_categorie,'products':all_product,'page':page})
    return render(request,'home.html',{ 'total_like':total_like,'total_cart':total_cart,'cat':pro_cats,'sliders':all_slides,'categories':all_categorie,'products':all_product,'page':page})

def slider(request):
    slider = sliders.objects.all()
    obj = sliderModelForm()

    if 'save' in request.POST:
        obj=sliderModelForm(request.POST,request.FILES)
        if obj.is_valid():
            obj.save()
        return redirect('/view_slider')
    return render(request,"add_slider.html",{'form':obj,'sliders':slider})

def view_slider(request):
    slider = sliders.objects.all()
    return render(request,'view_slider.html',{'sliders':slider})

def delete_slide(request,del_id2):
    print("ID=",del_id2)
    sliders.objects.filter(id=del_id2).delete()
    return redirect(request,'/view_slider')

def edit_slide(request,edit_id2):

    slide= sliders.objects.filter(id=edit_id2).get()
    if request.method == 'POST' :
        form = sliderModelForm(request.POST, request.FILES ,instance=slide)
        if form.is_valid():
            form.save()
            return redirect('/view_slider')
    else:
        form =  sliderModelForm(instance=slide)
    return redirect(request,'add_slider.html',{'form':form})

# categories ============================================================


def add_categorie(request):
    categorie = categories.objects.all()
    obj = categorieModelForm()

    if 'save' in request.POST:
        obj =categorieModelForm(request.POST,request.FILES)
        if obj.is_valid():
            obj.save()
        return redirect('/view_categorie')

    return render(request,'add_categorie.html',{'form':obj,'categories':categorie})


def view_categorie(request):
    categorie = categories.objects.all()
    return render(request,'view_categorie.html',{'categories':categorie})

def delete_categorie(request,del_id3):
    print("ID=",del_id3)
    categories.objects.filter(id=del_id3).delete()
    return redirect('/view_chefs')

def edit_categorie(request,edit_id3):
    categorie = categories.objects.filter(id=edit_id3).get()
    if request.method == 'POST':        
        form = categorieModelForm(request.POST, request.FILES, instance=categorie)
        if form.is_valid():
            form.save()
            return redirect('/view_categorie')
    else:
        
        form = categorieModelForm(instance=categorie)
        
        

    return render(request,'add_categorie.html',{'form':form})

# product ===============================================================================

def shop(request):
    # categories 
    pro_cats=categories.objects.all()

    user_id = request.session.get('page_id')
    all_carts = carts.objects.filter(user_id=user_id)
    total_cart = all_carts.aggregate(total=Sum('qty'))['total'] or 0

    all_likes = likes.objects.filter(user_id=user_id)
    total_like = all_likes.aggregate(total=Sum('user_id'))['total'] or 0

    all_product = products.objects.all()   
    return render(request,'shop.html',{'total_like':total_like,'total_cart':total_cart,'cat':pro_cats,'products':all_product})


# shop page 

def add_product(request):
    product = products.objects.all()
    obj = productModelForm()

    if 'save' in request.POST:
        obj =productModelForm(request.POST,request.FILES)
        if obj.is_valid():
            obj.save()
        return redirect('/view_product')
    return render(request,'add_product.html',{'form':obj,'products':product})

def view_product(request):
    product = products.objects.all()
    return render(request,'view_product.html',{'products':product})

def delete_product(request,del_id4):
    print("ID=",del_id4)
    products.objects.filter(id=del_id4).delete()
    return redirect('/view_product')

def edit_product(request,edit_id4):
    product = products.objects.filter(id=edit_id4).get()
    if request.method == 'POST':        
        form = productModelForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('/view_product')
    else:
            
        form = productModelForm(instance=product)
        
        

    return render(request,'add_product.html',{'form':form}) 

def add_cart_func(request,prod_id):
    product = products.objects.get(id=prod_id)
    u_id = request.session['page_id']
    checkExist = carts.objects.filter(product_id=prod_id,user_id=u_id)
    if checkExist.count()==0:    
        obj = carts(
            product_id = product,
            price = product.price,
            qty = 1,
            user_id = request.session['page_id']
        )
        obj.save()
    else:
        existRow = checkExist.get()
        existRow.qty = int(existRow.qty)+1
        existRow.save()
    return redirect('/cart');

def cart(request):
     # categories 
    pro_cats=categories.objects.all()

    if request.method == "POST":
        qty = request.POST['qty']
        cart_id = request.POST['cart_id']
        #product_id = request.POST['product_id']
        obj = carts.objects.filter(id=cart_id).get()
        obj.qty = qty
        obj.save()
   
    # product count..
    user_id = request.session.get('page_id')
    all_carts = carts.objects.filter(user_id=user_id)
    total_cart = all_carts.aggregate(total=Sum('qty'))['total'] or 0

    all_likes = likes.objects.filter(user_id=user_id)
    total_like = all_likes.aggregate(total=Sum('user_id'))['total'] or 0

    
    return render(request,'cart.html',{'total_like':total_like,'cat':pro_cats,'carts':all_carts,'total_cart': total_cart})

def delete_cart(request,del_id5):
    print("ID=",del_id5)
    carts.objects.filter(id=del_id5).delete()
    return redirect('/cart')

def edit_cart(request,edit_id5):
    
    cart = carts.objects.filter(id=edit_id5).get()
    if request.method == 'POST':        
        form = cartModelForm(request.POST, request.FILES, instance=cart)
        if form.is_valid():
            form.save()
            return redirect('/view_cart')
    else:
        
        form= cartModelForm(instance=cart)
    return render(request,'add_cart.html',{'form':form}) 

def add_like(request,prod_id):
    product = products.objects.get(id=prod_id)
    obj = likes(
        product_id = product,
        price = product.price,
        user_id = request.session['page_id']
    )
    obj.save()
    return redirect('/like');

def like(request):
     # categories 
    pro_cats=categories.objects.all()

    if request.method == "POST":
        like_id = request.POST['like_id']
        product_id = request.POST.get['product_id']
        obj = likes.objects.filter(id=like_id).get()
       
        obj.save()
   
    # product count..
    user_id = request.session.get('page_id')
    all_carts = carts.objects.filter(user_id=user_id)
    total_cart = all_carts.aggregate(total=Sum('qty'))['total'] or 0
    
    all_likes = likes.objects.filter(user_id=user_id)
    total_like = all_likes.aggregate(total=Sum('user_id'))['total'] or 0
   

    return render(request,'like.html',{'cat':pro_cats,'carts':all_carts,'total_cart': total_cart,'likes':all_likes,'total_like':total_like})

def delete_like(request,del_id7):
    print("ID=",del_id7)
    likes.objects.filter(id=del_id7).delete()
    return redirect('/like')
def checkout(request):
    return render(request,'checkout.html')

def user_login(request):
    
    if 'login' in  request.POST:
        email=request.POST['email']
        password=request.POST['password']
        page = contact.objects.filter(email=email,password=password)
        if page.count()==1:
            row = page.get()
            request.session['page_id']=row.id
            print(page.count())
            msg="valid"
            return redirect('/home')
        else:
            msg="invalid  email or password"
    return render(request,'user_login.html')

def contactpage(request):
    

    if 'save' in request.POST:
        Name=request.POST['name']
        Email=request.POST['email']
        Subject=request.POST['subject']
        Msg=request.POST['msg']
        Password=request.POST['password']
        
        obj = contact(
            name=Name,
            email=Email,
            subject=Subject,
            msg=Msg,
            password=Password,
        )
        obj.save()

        return redirect('/view_contact')
    return render(request,'contact.html')

def view_contact(request):
    data = contact.objects.all()
    return render(request,'view_contact.html',{'rows':data})

def product_detail(request,product_id):
     # categories 
    pro_cats=categories.objects.all()

    product = products.objects.filter(id=product_id).get()
    all_product = products.objects.all()
    
    # all_reviews = review.objects.filter(user_id=user_id)
    
    # cart
    cart = carts.objects.all()
    user_id = request.session.get('page_id')

    all_carts = carts.objects.filter(user_id=user_id)

userside/templates/add_cart.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'files/css/bootstrap.min.css'%}">
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table border="1">
            {{form}}

            <tr>
                <td></td>
                <td>
                    <input type="submit" name="save" value="save">
                </td>
            </tr>
        </table>
    </form>
    
    
    
</body>
</html>

userside/templates/add_product.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'files/css/bootstrap.min.css'%}">
</head>
<body>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <table border="1">
            {{form}}

            <tr>
                <td></td>
                <td>
                    <input type="submit" name="save" value="save">
                </td>
            </tr>
        </table>
    </form>
</body>
</html>

userside/templates/cart.html
{% load static%}
{% include 'header2.html'%}


<!-- Breadcrumb Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-12">
            <nav class="breadcrumb bg-light mb-30">
                <a class="breadcrumb-item text-dark" href="#">Home</a>
                <a class="breadcrumb-item text-dark" href="#">Shop</a>
                <span class="breadcrumb-item active">Shopping Cart</span>
            </nav>
        </div>
    </div>
</div>
<!-- Breadcrumb End -->


<!-- Cart Start -->
<div class="container-fluid">
    <div class="row px-xl-5">
        <div class="col-lg-8 table-responsive mb-5">
            <table class="table table-light table-borderless table-hover text-center mb-0">
                <thead class="thead-dark">
                    <tr>
                        <th>Products</th>
                        <th>Price</th>
                        <th>Quantity</th>
                        <th>add to cart</th>

                        <th>Total</th>
                        <th>Remove</th>
                    </tr>
                </thead>
                <tbody class="align-middle">
                    {% for cart in carts%}

                    <tr>
                        <form method="post">
                            {% csrf_token%}
                            <input type="hidden" name="cart_id" value="{{cart.id}}">
                            
                            <td class="align-middle"><img src="/media/{{cart.product_id.image}}" alt=""
                                    style="width: 50px;"> {{cart.product_id.name}}</td>
                            <td class="align-middle">${{cart.price}}</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary btn-minus">
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input name="qty" type="text"
                                        class="form-control form-control-sm bg-secondary border-0 text-center "
                                        value="{{ cart.qty }}" data-price="{{ cart.price }}">
                                    <div class="input-group-btn">
                                        <button type="button" class="btn btn-sm btn-primary btn-plus"  onclick="updateQuantity('{{ cart.id }}', '{{ cart.product_id.id }}', 'plus')">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td><button type="submit" name="update" value="Update">=</button></td>
                            <td class="align-middle">${{ cart.total_cost }}</td>

                            <td> <a href="/delete_cart/{{ cart.id }}">Delete</a></td>
                        </form>
                    </tr>
                    {%endfor%}

                    <!-- Display Cart Items -->


                </tbody>
            </table>
        </div>
        <div class="col-lg-4">
            <form class="mb-30" action="">
                <div class="input-group">
                    <input type="text" class="form-control border-0 p-4" placeholder="Coupon Code">
                    <div class="input-group-append">
                        <button class="btn btn-primary">Apply Coupon</button>
                    </div>
                </div>
            </form>
            <h5 class="section-title position-relative text-uppercase mb-3"><span class="bg-secondary pr-3">Cart
                    Summary</span></h5>
            <div class="bg-light p-30 mb-5">
                <div class="border-bottom pb-2">
                    <div class="d-flex justify-content-between mb-3">
                        <h6>Subtotal</h6>
                        <h6>$150</h6>
                    </div>
                    <div class="d-flex justify-content-between">
                        <h6 class="font-weight-medium">Shipping</h6>
                        <h6 class="font-weight-medium">$10</h6>
                    </div>
                </div>
                <div class="pt-2">
                    <div class="d-flex justify-content-between mt-2">
                        <h5>Total</h5>
                        <h5>$160</h5>
                    </div>
                    <button class="btn btn-block btn-primary font-weight-bold my-3 py-3">Proceed To Checkout</button>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->


{% include 'footer2.html'%}
<script>
    
</script>
</body>

</html>

userside/templates/home.html
{% load static%}
{% include 'header2.html'%}


    <!-- Carousel Start -->
    <div class="container-fluid mb-3">
        <div class="row px-xl-5">
            <div class="col-lg-8">
                <div id="header-carousel" class="carousel slide carousel-fade mb-30 mb-lg-0" data-ride="carousel">
                    <ol class="carousel-indicators">
                        <li data-target="#header-carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#header-carousel" data-slide-to="1"></li>
                        <li data-target="#header-carousel" data-slide-to="2"></li>
                    </ol>

                    <div class="carousel-inner">
                        {% for slide in sliders%}
                        <div class="carousel-item position-relative {% if forloop.counter0 == 0 %}active{%endif%}" style="height: 430px;">
                            <img class="position-absolute w-100 h-100" src="/media/{{slide.image}}" style="object-fit: cover;">
                            <div class="carousel-caption d-flex flex-column align-items-center justify-content-center">
                                <div class="p-3" style="max-width: 700px;">
                                    <h1 class="display-4 text-white mb-3 animate__animated animate__fadeInDown">Men Fashion</h1>
                                    <p class="mx-md-5 px-5 animate__animated animate__bounceIn">Lorem rebum magna amet lorem magna erat diam stet. Sadips duo stet amet amet ndiam elitr ipsum diam</p>
                                    <a class="btn btn-outline-light py-2 px-4 mt-3 animate__animated animate__fadeInUp" href="#">Shop Now</a>
                                </div>
                            </div>
                        </div>
                        {%endfor%}
                        
                        
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="product-offer mb-30" style="height: 200px;">
                    <img class="img-fluid" src="{% static 'img/offer-1.jpg' %}" alt="">
                    <div class="offer-text">
                        <h6 class="text-white text-uppercase">Save 20%</h6>
                        <h3 class="text-white mb-3">Special Offer</h3>
                        <a href="" class="btn btn-primary">Shop Now</a>
                    </div>
                </div>
                <div class="product-offer mb-30" style="height: 200px;">
                    <img class="img-fluid" src="{% static 'img/offer-2.jpg' %}" alt="">
                    <div class="offer-text">
                        <h6 class="text-white text-uppercase">Save 20%</h6>
                        <h3 class="text-white mb-3">Special Offer</h3>
                        <a href="" class="btn btn-primary">Shop Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Carousel End -->


    <!-- Featured Start -->
    <div class="container-fluid pt-5">
        <div class="row px-xl-5 pb-3">
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                    <h1 class="fa fa-check text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">Quality Product</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                    <h1 class="fa fa-shipping-fast text-primary m-0 mr-2"></h1>
                    <h5 class="font-weight-semi-bold m-0">Free Shipping</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                    <h1 class="fas fa-exchange-alt text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">14-Day Return</h5>
                </div>
            </div>
            <div class="col-lg-3 col-md-6 col-sm-12 pb-1">
                <div class="d-flex align-items-center bg-light mb-4" style="padding: 30px;">
                    <h1 class="fa fa-phone-volume text-primary m-0 mr-3"></h1>
                    <h5 class="font-weight-semi-bold m-0">24/7 Support</h5>
                </div>
            </div>
        </div>
    </div>
    <!-- Featured End -->


    <!-- Categories Start -->
    <div class="container-fluid pt-5">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Categories</span></h2>
        <a href="/add_categorie">Categories</a>
        <div class="row px-xl-5 pb-3">
            {% for categorie in categories%}
            <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                <a class="text-decoration-none" href="/catagory/{{categorie.id }}">
                    <div class="cat-item d-flex align-items-center mb-4">
                        <div class="overflow-hidden" style="width: 100px; height: 100px;">
                            <img class="img-fluid" src="/media/{{categorie.image}}" alt="">
                        </div>
                        <div class="flex-fill pl-3">
                            <h6>{{categorie.title}}</h6>
                            
                            <small class="text-body">{{categorie.products_set.count}} Products</small>
                        </div>
                    </div>
                </a>
            </div>
            {%endfor%}
        </div>
    </div>
    <!-- Categories End -->


    <!-- Products Start -->
    <div class="container-fluid pt-5 pb-3">
        <h2 class="section-title position-relative text-uppercase mx-xl-5 mb-4"><span class="bg-secondary pr-3">Featured Products</span></h2>
        <a href="/add_product">product</a>
        <div class="row px-xl-5">
            {% for product in products%}
            <div class="col-lg-3 col-md-4 col-sm-6 pb-1">
                <div class="product-item bg-light mb-4">
                    <div class="product-img position-relative overflow-hidden">
                        <img class="img-fluid w-100" src="/media/{{product.image}}" alt="">
                        <div class="product-action">
                            <a class="btn btn-outline-dark btn-square" href="/add_cart/{{product.id}}"><i class="fa fa-shopping-cart"></i></a>
                            <a class="btn btn-outline-dark btn-square" href="/add_like/{{product.id}}"><i class="far fa-heart"></i></a>
                            <a class="btn btn-outline-dark btn-square" href=""><i class="fa fa-sync-alt"></i></a>
                            <a class="btn btn-outline-dark btn-square" href="/product_detail/{{ product.id }}"><i class="fa fa-search"></i></a>
                        </div>
                    </div>
                    <div class="text-center py-4">
                        <a class="h6 text-decoration-none text-truncate" href="">{{product.name}} Goes Here</a>
                        <div class="d-flex align-items-center justify-content-center mt-2">
                            <h5>${{product.price}}</h5><h6 class="text-muted ml-2"><del>${{product.price}}</del></h6>
                        </div>
                        <div class="d-flex align-items-center justify-content-center mb-1">
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small class="fa fa-star text-primary mr-1"></small>
                            <small>(99)</small>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
            
        </div>
    </div>
    <!-- Products End -->


    <!-- Offer Start -->
    <div class="container-fluid pt-5 pb-3">
        <div class="row px-xl-5">
            <div class="col-md-6">
                <div class="product-offer mb-30" style="height: 300px;">
                    <img class="img-fluid" src="{% static 'img/offer-1.jpg' %}" alt="">
                    <div class="offer-text">
                        <h6 class="text-white text-uppercase">Save 20%</h6>
                        <h3 class="text-white mb-3">Special Offer</h3>
                        <a href="" class="btn btn-primary">Shop Now</a>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="product-offer mb-30" style="height: 300px;">
                    <img class="img-fluid" src="{% static 'img/offer-2.jpg' %}" alt="">
                    <div class="offer-text">
                        <h6 class="text-white text-uppercase">Save 20%</h6>
                        <h3 class="text-white mb-3">Special Offer</h3>
                        <a href="" class="btn btn-primary">Shop Now</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Offer End -->


    


    <!-- Vendor Start -->
    <a href="/add_cart"></a>
    <div class="container-fluid py-5">
        <div class="row px-xl-5">
            <div class="col">
                <div class="owl-carousel vendor-carousel">
                    <div class="bg-light p-4">
                        <img src="{% static 'img/vendor-1.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'img/vendor-2.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'img/vendor-3.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'img/vendor-4.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'img/vendor-5.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'img/vendor-6.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'img/vendor-7.jpg' %}" alt="">
                    </div>
                    <div class="bg-light p-4">
                        <img src="{% static 'img/vendor-8.jpg' %}" alt="">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Vendor End -->

    {% include 'footer2.html'%}
</body>

</html>